[projects.cd]
path = 'Source\TestCD Custom Device.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'


[package]
type = 'nipkg'
name = 'test-custom-device-{veristand_version}'
dev_xml_path = 'Source\Custom Device TestCD.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices'
